(function(){
  const reduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
  const root=document.documentElement;
  const themeButton=document.createElement('button');themeButton.id='theme-button';themeButton.className='quiet theme-switch';
  document.querySelector('header').insertBefore(themeButton,document.querySelector('#rules-button'));
  function setTheme(theme){root.dataset.theme=theme;themeButton.textContent=theme==='dark'?'☀ 日间模式':'☾ 夜间模式';themeButton.setAttribute('aria-label',theme==='dark'?'切换日间模式':'切换夜间模式');themeButton.setAttribute('aria-pressed',String(theme==='dark'))}
  setTheme(root.dataset.theme||'light');themeButton.onclick=()=>{const theme=root.dataset.theme==='dark'?'light':'dark';setTheme(theme);try{localStorage.setItem('strength-cards:theme',theme)}catch{}};
  let drag=null,suppressUntil=0;
  const clean=()=>{if(!drag)return;clearTimeout(drag.timer);cancelAnimationFrame(drag.frame);drag.ghost?.remove();drag.tray?.remove();drag.el.classList.remove('held');document.body.classList.remove('dragging-card');document.querySelectorAll('.drag-over').forEach(el=>el.classList.remove('drag-over'));drag=null};
  function targetAt(x,y){const el=document.elementFromPoint(x,y);return el?.closest('[data-drop-row], [data-row]')}
  function update(){if(!drag?.active)return;drag.ghost.style.left=drag.x+'px';drag.ghost.style.top=drag.y+'px';const target=targetAt(drag.x,drag.y);document.querySelectorAll('.drag-over').forEach(el=>el.classList.toggle('drag-over',el===target));target?.classList.add('drag-over');drag.row=target?Number(target.dataset.dropRow??target.dataset.row):null}
  function scrollFrame(){if(!drag?.active)return;const edge=80;let speed=0;if(drag.y<edge)speed=-Math.ceil((edge-drag.y)/7);else if(drag.y>innerHeight-145&&drag.y<innerHeight-72)speed=Math.ceil((drag.y-(innerHeight-145))/5);if(speed)window.scrollBy(0,speed);update();drag.frame=requestAnimationFrame(scrollFrame)}
  function begin(){if(!drag||drag.active)return;drag.active=true;drag.el.classList.add('held');document.body.classList.add('dragging-card');const ghost=drag.el.cloneNode(true);ghost.className='mini-card drag-ghost';ghost.removeAttribute('id');ghost.removeAttribute('data-select');ghost.removeAttribute('data-drag');ghost.setAttribute('aria-hidden','true');ghost.style.width=Math.min(240,Math.max(180,drag.el.getBoundingClientRect().width))+'px';document.body.append(ghost);drag.ghost=ghost;const tray=document.createElement('div');tray.className='drop-tray';tray.setAttribute('aria-hidden','true');tray.innerHTML='<span>松开放入</span>'+['非常符合','比较符合','一般符合','不太符合'].map((name,i)=>'<div data-drop-row="'+i+'"><b>'+[5,3,1,0][i]+'</b><small>'+name+'</small></div>').join('');document.body.append(tray);drag.tray=tray;update();drag.frame=requestAnimationFrame(scrollFrame)}
  function prepare(el,x,y,kind,move){clean();drag={el,id:Number(el.dataset.drag),x,y,startX:x,startY:y,kind,move,active:false,row:null};drag.timer=setTimeout(begin,280)}
  function moved(x,y,e){if(!drag)return;drag.x=x;drag.y=y;const distance=Math.hypot(x-drag.startX,y-drag.startY);if(!drag.active&&distance>9){if(drag.kind==='mouse')begin();else{clean();return}}if(drag?.active){if(e.cancelable)e.preventDefault();update()}}
  function end(e){if(!drag)return;const current=drag;if(current.active){if(e?.cancelable)e.preventDefault();suppressUntil=Date.now()+450;const target=current.row;clean();if(target!==null)current.move(current.id,target)}else clean()}
  document.addEventListener('pointermove',e=>{if(drag?.kind==='mouse')moved(e.clientX,e.clientY,e)},{passive:false});
  document.addEventListener('pointerup',e=>{if(drag?.kind==='mouse')end(e)});
  document.addEventListener('pointercancel',()=>{if(drag?.kind==='mouse')clean()});
  document.addEventListener('touchmove',e=>{if(drag?.kind==='touch'&&e.touches.length===1)moved(e.touches[0].clientX,e.touches[0].clientY,e)},{passive:false});
  document.addEventListener('touchend',e=>{if(drag?.kind==='touch')end(e)},{passive:false});
  document.addEventListener('touchcancel',clean);window.addEventListener('blur',clean);
  document.addEventListener('keydown',e=>{if(e.key==='Escape')clean()});
  document.addEventListener('click',e=>{if(Date.now()<suppressUntil){e.preventDefault();e.stopImmediatePropagation()}},true);
  function bindDrag(move){document.querySelectorAll('[data-drag]').forEach(el=>{el.draggable=false;el.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||e.button!==0)return;prepare(el,e.clientX,e.clientY,'mouse',move)});el.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;const p=e.touches[0];prepare(el,p.clientX,p.clientY,'touch',move);if(e.target.closest('.drag-grip'))begin()},{passive:true});el.addEventListener('contextmenu',e=>e.preventDefault())})}
  function placement(id,row,before){const card=document.querySelector('[data-select="'+id+'"]');const destination=document.querySelector('[data-row="'+row+'"]');destination?.classList.add('just-placed');setTimeout(()=>destination?.classList.remove('just-placed'),650);if(!reduced()&&card?.animate){const end=card.getBoundingClientRect();if(before&&Math.abs(before.top-end.top)<innerHeight*1.3)card.animate([{transform:'translate('+ (before.left-end.left)+'px,'+(before.top-end.top)+'px) scale(.92)',opacity:.4},{transform:'translate(0,0) scale(1)',opacity:1}],{duration:420,easing:'cubic-bezier(.2,.8,.2,1)'});else card.animate([{transform:'scale(.85)',opacity:.3},{transform:'scale(1)',opacity:1}],{duration:350})}}
  function celebrate(){if(reduced())return;const layer=document.createElement('div');layer.className='celebration';layer.setAttribute('aria-hidden','true');for(let i=0;i<36;i++){const dot=document.createElement('i');dot.style.cssText='--x:'+Math.random()*100+'vw;--dx:'+(Math.random()-.5)*240+'px;--delay:'+Math.random()*.3+'s;--spin:'+(Math.random()*720-360)+'deg;background:'+['#40bfa6','#79a5ff','#c4a0ef','#ffb360','#ed85a4'][i%5];layer.append(dot)}document.body.append(layer);setTimeout(()=>layer.remove(),2400)}
  window.GameEffects={bindDrag,placement,celebrate};
})();
