const GROUPS = [
 {name:'学习力',color:'#72b5fa',ink:'#164779',family:'思维',note:'从未知里获得能量，把新知识变成理解。',cards:[['思想开放','杂而不精','乐于接受一切新鲜事物，不断突破自己的认知边界','喜欢接受新观点，乐于从不同立场中获得启发'],['求知欲','学而无用','一旦对某个事情感兴趣，就会去了解这个事情的方方面面','学习到新知识，会感到充实、兴奋'],['搜索','学以逃避','喜欢从各种渠道获取资讯并对有用的信息收藏保存','感觉任何资源都有潜在的用途，不忍割舍']]},
 {name:'创新力',color:'#bc9cff',ink:'#4b2d81',family:'思维',note:'连接不同的想法，为熟悉的问题打开新可能。',cards:[['跳脱','不切实际','放松的时候会做很多幻想','可以将不相关的东西建立关联，脑洞较大','追求轻松和自由自在'],['灵活','流于表面','善于举一反三，触类旁通','对一个问题能进行多角度思考，找到多个解决办法','遇到计划之外的状况，也能快速应变'],['革新','缺乏定力','喜欢打破常规的做事方法','喜欢把常见的东西挖掘新的用途']]},
 {name:'分析力',color:'#5bd7d7',ink:'#13595e',family:'思维',note:'拆解复杂问题，用关联、细节和证据形成判断。',cards:[['精准','辩论思维','注重细节，对“错误”非常敏感','喜欢使用明确的数据支撑判断和决策'],['全局','选择困难','喜欢拆解复杂问题，做出思维导图','厌恶孤立信息，喜欢探究事件的关联性','通常会思考全面再行动'],['逻辑','怯于行动','喜欢从现象中挖掘背后的原因和本质','喜欢研究、拆解方法论']]},
 {name:'交往力',color:'#ffad72',ink:'#7c3b15',family:'关系',note:'主动建立连接，在交流中形成信任与亲近。',cards:[['主动','利益羞耻','喜欢在社交场合主动与人打招呼，积极结识新朋友','待人热情，乐于分享'],['信任','误信默契','容易信任他人，相信他人是带着善意的','即使刚认识，也能说出很多自己的事情'],['亲密','回避冲突','会主动用行动和言语表达对他人的喜欢','会和朋友分享内心深处最真实的情感']]},
 {name:'共情力',color:'#ee9eca',ink:'#762b58',family:'关系',note:'感知他人的处境，在倾听与支持中建立理解。',cards:[['平和宽容','压抑委屈','能包容他人的不足，接纳不同的观点','重视团队氛围，不喜欢冲突'],['支持','不由自主','擅长倾听给予他人情感支持和鼓励','会力所能及地帮助他人'],['体察','共情过载','很容易陷入到电影人物的情感世界，泪点低','很容易体察到别人的情绪，容易换位思考']]},
 {name:'引领力',color:'#f6ce67',ink:'#6e5011',family:'关系',note:'表达方向、作出决策，也承担带头前进的责任。',cards:[['统领','过度管控','比起服从，更喜欢指挥','喜欢起带头作用','敢于做决策，也愿意为决策负责'],['自信','大成大败','对未来充满信心','感觉自己有能力应对各种困难','非常相信自己的判断，并为此负责'],['表达','好为人师','比起倾听，更会擅长表达','有信心说服别人接受我的观点']]},
 {name:'目标力',color:'#90d979',ink:'#305d20',family:'执行',note:'保持方向与节奏，把注意力留给真正重要的目标。',cards:[['坚持','拖延目标','在达成目标前，通常不会轻言放弃','不会轻易动摇内心想法始终如一'],['计划','缺乏闯劲','喜欢制定各种行动计划','注重过程是否正确，流程是否有序'],['专注','窄窗思维','一旦确定方向，就会摒除外界干扰','能够长时间集中精力保持在同一任务上的高效投入']]},
 {name:'行动力',color:'#ff897c',ink:'#802f28',family:'执行',note:'在尝试中获得反馈，把想法推进到真实世界。',cards:[['决断','有始无终','能从多个看起来差不多的选项中迅速做抉择','即使很紧急的情况，大脑仍然能保持高速运转'],['挑战','冒进溃败','敢于尝试不怕失败','喜欢刺激和挑战的项目','对于想做的事，很少考虑其风险'],['行动','急于求成','喜欢边做边想','接到新任务会快速响应','想到就希望立刻动手做']]},
 {name:'驱动力',color:'#939eff',ink:'#363f83',family:'执行',note:'由成就、竞争或信念驱动，持续追求更有价值的成果。',cards:[['竞争','回避竞争','自我要求高，不服输','愿意尝试别人做不到的事','渴望胜利，获得第一'],['成就','永不满足','非常渴望有所建树，达到更高的层次','无论是工作日还是休息日，每天都会想要追求有所成果'],['信念','理想空悬','心中有想要追求的理想','特别重视工作的意义感和自我价值','始终遵循内心的准则和价值观，不轻易动摇']]}
];
const CARDS=GROUPS.flatMap((g,gi)=>g.cards.map((c,ci)=>({id:gi*3+ci,group:gi,light:c[0],shadow:c[1],lines:c.slice(2)})));
const ROWS=[{label:'非常符合',score:5,hint:'经常如此，也很自然'},{label:'比较符合',score:3,hint:'多数时候符合我'},{label:'一般符合',score:1,hint:'偶尔如此，看情况'},{label:'不太符合',score:0,hint:'很少如此，或不像我'}];
const CAREERS=[
 {title:'研究与洞察',roles:'市场研究、用户研究、行业分析',groups:[0,2,4],why:'学习帮助你进入新领域，分析帮助你形成证据，共情帮助你理解需求。',try:'选择一个感兴趣的问题，访谈 3 个人，用一页纸整理发现。',url:'https://www.onetonline.org/link/summary/13-1161.00'},
 {title:'创意与产品设计',roles:'产品设计、工业设计、创意策划',groups:[1,0,2],why:'用学习拓宽素材，以创新提出方案，再通过分析检验可行性。',try:'为一个日常不便设计 3 种方案，做一个可试用的简单原型。',url:'https://www.onetonline.org/link/summary/27-1021.00'},
 {title:'项目与运营推进',roles:'项目管理、活动运营、实施顾问',groups:[6,7,5],why:'目标力让流程有序，行动力推动落地，引领力帮助协调决策。',try:'组织一次小型活动，负责计划、分工、执行与复盘。',url:'https://www.onetonline.org/link/summary/13-1082.00'},
 {title:'培训与人才发展',roles:'企业培训、学习发展、课程设计',groups:[4,0,5],why:'学习帮助梳理内容，共情帮助理解学习者，表达与引领帮助带动参与。',try:'把熟悉的技能设计成一堂 20 分钟的小课，收集学习反馈。',url:'https://www.onetonline.org/link/summary/13-1151.00'},
 {title:'沟通与关系拓展',roles:'公共关系、商务拓展、客户关系',groups:[3,5,8],why:'交往力打开连接，引领力支持沟通说服，驱动力帮助持续推进。',try:'为一个真实项目联络潜在合作伙伴，记录需求与下一步。',url:'https://www.onetonline.org/link/summary/27-3031.00'},
 {title:'团队与业务经营',roles:'团队负责人、业务运营、创业项目探索',groups:[5,8,6],why:'引领力明确方向，驱动力支撑投入，目标力帮助把意愿变成计划。',try:'带领一个小项目完成一次可衡量的交付，观察自己是否享受这个过程。',url:'https://www.onetonline.org/link/summary/11-1021.00'}
];
const app=document.querySelector('#app');
const state={phase:'sort',order:CARDS.map(c=>c.id).sort(()=>Math.random()-.5),places:Array(27).fill(null),selected:null,flipped:false,history:[],top:[],tie:[]};
const counts=()=>ROWS.map((_,r)=>state.places.filter(p=>p===r).length);
const placed=()=>state.places.filter(p=>p!==null).length;
const balanced=()=>placed()===27&&counts().every(n=>n>=6&&n<=7);
const nextCard=()=>state.order.find(id=>state.places[id]===null);
const activeCard=()=>state.selected??nextCard();
const theme=g=>`--card:${g.color};--ink:${g.ink}`;
const ranking=()=>GROUPS.map((g,i)=>({...g,id:i,score:CARDS.filter(c=>c.group===i).reduce((s,c)=>s+(state.places[c.id]===null?0:ROWS[state.places[c.id]].score),0)})).sort((a,b)=>b.score-a.score||a.id-b.id);
function notify(message){const el=document.querySelector('#status');el.textContent=message;el.classList.add('visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.classList.remove('visible'),4000)}
function render(){
 saveProgress();
 if(state.phase==='results'){renderResults();return}
 const isBalance=state.phase==='balance';const n=placed();const id=activeCard();
 app.innerHTML=`<nav class="steps" aria-label="游戏进度">${['初步分类','均衡调整','揭晓优势'].map((s,i)=>`<span class="${i===(isBalance?1:0)?'current':''}"><b>${i+1}</b>${s}</span>`).join('<i></i>')}</nav>
 <div class="heading"><div><p class="eyebrow">${isBalance?'02 / 做一点取舍':'01 / 凭直觉分类'}</p><h1>${isBalance?'让真正的偏好，浮到前面。':'从日常里的你，找到发光面。'}</h1><p>${isBalance?'比较卡片的相对符合程度，调整到每行 6–7 张。':'想想最近半年真实的自己，阅读描述，把卡片放进合适的一行。'}</p></div><div class="progress-block"><strong>${n}<span> / 27</span></strong><label for="game-progress">${isBalance?'张卡片已归位':'张卡片已分类'}</label><progress id="game-progress" value="${n}" max="27">${n}/27</progress></div></div>
 <section class="workspace" aria-label="优势卡牌分类桌"><aside class="card-dock"><div class="dock-title"><span>${state.selected!==null?'正在查看':'待分类卡片'}</span><span>${state.selected!==null?`已放入 · ${ROWS[state.places[id]].label}`:`剩余 ${27-n} 张`}</span></div><div id="card-area">${id!==undefined?cardHTML(CARDS[id]):`<div class="all-done"><span>✦</span><h2>${isBalance?'每一次取舍，<br>都让你更了解自己。':'27 张牌，<br>初步分类完成。'}</h2><p>${isBalance?'点击任意一张桌面卡片，查看完整描述或移动。':'接下来，比较四行卡片，让每行保留 6–7 张。'}</p></div>`}</div>
 ${id!==undefined?`<p class="card-help">${state.selected!==null?'选中后点击下方按钮，或拖到另一行。':'点击下方分数放置，也可拖入右侧牌桌。'}</p><div class="quick-choices">${ROWS.map((r,i)=>`<button data-place="${i}" ${counts()[i]>=12&&state.places[id]!==i?'disabled':''} aria-label="放入${r.label}，${r.score}分"><strong>${r.score}</strong><span>${r.label}</span></button>`).join('')}</div>`:''}
 ${state.selected!==null?'<button class="text-button full" data-action="deselect">← 返回待分类卡片 / 牌桌</button>':''}<div class="dock-foot"><span>没有好坏之分，按真实感受选择。</span><button class="text-button" data-action="undo" ${!state.history.length?'disabled':''}>↶ 撤销</button></div></aside>
 <div class="table"><div class="table-caption"><span>你的分类牌桌</span><span>${isBalance?'目标：7 / 7 / 7 / 6，顺序不限':'每行暂可放 12 张'}</span></div>${ROWS.map((r,i)=>rowHTML(r,i,isBalance)).join('')}
 <div class="table-bottom"><p>${isBalance?balanceHint():'先按直觉分完所有卡片，再一起调整。'}</p><button class="primary" data-action="${isBalance?'submit':'balance'}" ${isBalance?!balanced()?'disabled':'':n!==27?'disabled':''}>${isBalance?'揭晓我的优势 ✦':'下一步：均衡调整 →'}</button></div>${isBalance?'<button class="text-button" data-action="sort">← 返回初步分类</button>':''}</div></section>`;
 bind();
}
function cardHTML(c){const g=GROUPS[c.group];return `<button class="big-card ${state.flipped?'is-flipped':''}" style="${theme(g)}" data-action="flip" draggable="true" data-drag="${c.id}" aria-label="卡片 ${c.id+1}，点击翻面" aria-pressed="${state.flipped}"><span class="card-inner"><span class="card-face front" aria-hidden="${state.flipped}"><span class="card-top">日常里的我 <b>${String(c.id+1).padStart(2,'0')} / 27</b></span><span class="card-statements">${c.lines.map((l,i)=>`<span class="statement"><span class="line-dot">${String(i+1).padStart(2,'0')}</span>${l}</span>`).join('')}</span><span class="card-bottom">按整体符合程度判断 <span>翻面 ↻</span></span></span><span class="card-face back" aria-hidden="${!state.flipped}"><span class="card-top">${g.family}维度 <b>优势档案</b></span><span class="back-name">${g.name}</span><span class="back-label">发光面</span><strong class="light-name">${c.light}</strong><span class="shadow-box"><span>阴影面</span><strong>${c.shadow}</strong></span><span class="back-note">阴影面用于复盘提醒，不参与评分。</span><span class="card-bottom">排序请依据正面描述 <span>翻回 ↻</span></span></span></span></button>`}
function rowHTML(r,i,isBalance){const ids=state.order.filter(id=>state.places[id]===i);const ok=ids.length>=6&&ids.length<=7;return `<section class="card-row ${isBalance?(ok?'row-good':'row-needs'):''}" data-row="${i}" aria-label="${r.label}，${r.score}分，${ids.length}张"><div class="row-label"><button class="row-score" data-place="${i}" aria-label="将所选卡片放入${r.label}">${r.score}</button><div><h2>${r.label}</h2><small>${r.hint}</small></div><span class="row-count">${ids.length}<small> / ${isBalance?'6–7':'12'}</small>${isBalance&&ok?' ✓':''}</span></div><div class="row-cards">${ids.length?ids.map(id=>{const c=CARDS[id],g=GROUPS[c.group];return `<button class="mini-card ${state.selected===id?'selected':''}" style="${theme(g)}" draggable="true" data-drag="${id}" data-select="${id}" aria-label="查看第${id+1}张卡片：${c.lines.join('；')}"><span>${String(id+1).padStart(2,'0')}</span><p>${c.lines[0]}</p></button>`}).join(''):`<button class="empty-row" data-place="${i}"><span>＋</span> ${activeCard()!==undefined?'点击放入所选卡片，或拖到这里':'这里还没有卡片'}</button>`}</div></section>`}
function balanceHint(){const c=counts();if(balanced())return '四行已均衡，可以揭晓结果了。';return c.map((n,i)=>n>7?`${ROWS[i].label}移出至少 ${n-7} 张`:n<6?`${ROWS[i].label}补入至少 ${6-n} 张`:null).filter(Boolean).join('；')+'。'}
function moveCard(id,row){if(state.phase==='results'||!Number.isInteger(id)||id<0||id>=27||!Number.isInteger(row)||row<0||row>3)throw Error('卡片或分类无效');if(state.places[id]===row)return;if(counts()[row]>=12){notify('这一行已有 12 张，请先移出一张再放入。');return false}state.history.push({id,from:state.places[id]});state.places[id]=row;state.selected=null;state.flipped=false;state.top=[];render();notify(`第 ${id+1} 张卡片已放入「${ROWS[row].label}」`);return true}
function bind(){
 document.querySelectorAll('[data-place]').forEach(el=>el.onclick=()=>{const id=activeCard();if(id===undefined){notify('先点击一张桌面卡片，再选择要移入的分类。');return}moveCard(id,Number(el.dataset.place))});
 document.querySelectorAll('[data-select]').forEach(el=>el.onclick=()=>{state.selected=Number(el.dataset.select);state.flipped=false;render();if(innerWidth<850)document.querySelector('.card-dock').scrollIntoView({behavior:'smooth',block:'start'})});
 document.querySelectorAll('[data-drag]').forEach(el=>el.ondragstart=e=>{e.dataTransfer.setData('text/plain',el.dataset.drag);e.dataTransfer.effectAllowed='move'});
 document.querySelectorAll('[data-row]').forEach(el=>{el.ondragover=e=>{e.preventDefault();el.classList.add('drag-over')};el.ondragleave=()=>el.classList.remove('drag-over');el.ondrop=e=>{e.preventDefault();el.classList.remove('drag-over');const raw=e.dataTransfer.getData('text/plain');if(/^\d+$/.test(raw))moveCard(Number(raw),Number(el.dataset.row))}});
 document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action));
}
function action(a){if(a==='flip'){state.flipped=!state.flipped;const c=document.querySelector('.big-card');c.classList.toggle('is-flipped',state.flipped);c.setAttribute('aria-pressed',String(state.flipped));c.querySelector('.front').setAttribute('aria-hidden',String(state.flipped));c.querySelector('.back').setAttribute('aria-hidden',String(!state.flipped));return}
 if(a==='undo'){const h=state.history.pop();if(h){state.places[h.id]=h.from;state.selected=null;state.flipped=false;render();notify('已撤销上一次移动')}return}
 if(a==='deselect'){state.selected=null;state.flipped=false;render();return}
 if(a==='balance'){if(placed()!==27)return;state.phase='balance';state.selected=null;state.flipped=false;render();window.scrollTo({top:0,behavior:'smooth'});return}
 if(a==='sort'||a==='edit'){state.phase=a==='edit'?'balance':'sort';state.selected=null;state.flipped=false;render();window.scrollTo({top:0,behavior:'smooth'});return}
 if(a==='submit'){submit();return}if(a==='restart'){openDialog('重新探索','<p>这会开始新一轮分类，并重新洗牌。已提交的结果仍保留在“历史结果”中。</p><button class="primary" id="confirm-reset">确认重新开始</button>');document.querySelector('#confirm-reset').onclick=()=>{closeDialog();state.phase='sort';state.places.fill(null);state.order.sort(()=>Math.random()-.5);state.selected=null;state.flipped=false;state.history=[];state.top=[];state.tie=[];render();window.scrollTo({top:0})};return}}
function submit(){if(!balanced()){notify('请先将 27 张卡片调整为每行 6–7 张。');return}const ranks=ranking(),cut=ranks[3].score,above=ranks.filter(g=>g.score>cut),ties=ranks.filter(g=>g.score===cut),slots=4-above.length;if(ties.length>slots){state.tie=[];openDialog('第 4 名出现了并列',`<p>以下 ${ties.length} 项同为 <strong>${cut} 分</strong>。请选择 ${slots} 项作为优先探索的优势；分数与并列排名保持不变。</p><div class="tie-options">${ties.map(g=>`<label style="${theme(g)}"><input type="checkbox" value="${g.id}"><span><strong>${g.name}</strong><small>${g.note}</small></span></label>`).join('')}</div><button id="confirm-tie" class="primary full" disabled>请选择 ${slots} 项</button>`);document.querySelectorAll('.tie-options input').forEach(el=>el.onchange=()=>{state.tie=[...document.querySelectorAll('.tie-options input:checked')].map(x=>Number(x.value));const b=document.querySelector('#confirm-tie');b.disabled=state.tie.length!==slots;b.textContent=`确认优先探索（${state.tie.length} / ${slots}）`});document.querySelector('#confirm-tie').onclick=()=>{if(state.tie.length!==slots)return;state.top=[...above.map(g=>g.id),...state.tie];closeDialog();finish()};return}state.top=ranks.slice(0,4).map(g=>g.id);finish()}
function finish(){state.phase='results';StrengthStorage.remember(state);render();window.scrollTo({top:0,behavior:'smooth'})}
function renderResults(){const ranks=ranking(),tops=ranks.filter(g=>state.top.includes(g.id));const careers=CAREERS.map((c,index)=>({...c,index,weight:c.groups.reduce((s,id)=>s+ranks.find(g=>g.id===id).score+(state.top.includes(id)?3:0),0)})).sort((a,b)=>b.weight-a.weight||a.index-b.index).slice(0,3);
 app.innerHTML=`<nav class="steps" aria-label="游戏进度"><span><b>✓</b>初步分类</span><i></i><span><b>✓</b>均衡调整</span><i></i><span class="current"><b>3</b>揭晓优势</span></nav><div class="result-heading"><p class="eyebrow">03 / 你的优势画像</p><h1>这些日常倾向，<br>正在成为你的力量。</h1><p>本轮优先探索的四项优势。把它们带回真实生活，看看在哪里最能发挥。</p><div class="result-orbit" aria-hidden="true">✦</div></div><section class="top-grid" aria-label="前四优势">${tops.map((g,i)=>`<article class="top-card" style="${theme(g)};--delay:${i*110}ms"><span class="top-meta">${g.family}维度 <b>${g.score} <small>/ 15</small></b></span><h2>${g.name}</h2><p>${g.note}</p><div class="chips">${g.cards.map(c=>`<span>${c[0]}</span>`).join('')}</div>${state.tie.includes(g.id)?'<small>并列中由你选择优先探索</small>':''}</article>`).join('')}</section>
 <div class="result-columns"><section class="rank-panel"><div class="section-title"><h2>九项优势 · 全部得分</h2><span>每项满分 15</span></div><p class="muted">同一优势的三张卡片相加；同分保留并列。</p><div class="rank-chart">${ranks.map((g,i)=>{const rank=ranks.findIndex(x=>x.score===g.score)+1;return `<div class="rank-row" style="${theme(g)};--delay:${i*95}ms"><span class="rank-number">${String(rank).padStart(2,'0')}</span><span>${g.name}</span><div class="bar-track"><div class="bar" style="--width:${g.score/15*100}%"></div></div><strong data-score="${g.score}">0</strong><span class="rank-mark">${state.top.includes(g.id)?'✦':''}</span></div>`}).join('')}</div><details class="score-detail"><summary>查看每张卡片的计分依据</summary>${ranks.map(g=>`<div class="score-group"><h3 style="color:${g.color}">${g.name} · ${g.score} 分</h3>${CARDS.filter(c=>c.group===g.id).map(c=>`<p><span>${c.light}<small>阴影面：${c.shadow}</small></span><span>${ROWS[state.places[c.id]].label} <b>+${ROWS[state.places[c.id]].score}</b></span></p>`).join('')}</div>`).join('')}</details><p class="fine-print">本轮分布：${counts().map((n,i)=>`${ROWS[i].score} 分区 ${n} 张`).join(' · ')}。强制取舍反映本轮的相对偏好，低分不代表缺乏能力。</p></section>
 <section class="career-panel"><div class="section-title"><h2>值得探索的职业方向</h2><span>从一次小尝试开始</span></div><p class="muted">按优势组合生成的启发式建议，不是职业适配概率；还需结合技能、兴趣与经历。</p>${careers.map((c,i)=>`<article class="career"><span class="career-number">0${i+1}</span><div><h3>${c.title}</h3><p class="roles">${c.roles}</p><div class="career-tags">${c.groups.map(id=>`<span style="color:${GROUPS[id].color}">${GROUPS[id].name}</span>`).join('')}</div><p>${c.why}</p><p class="try"><b>小尝试</b>${c.try}</p><a href="${c.url}" target="_blank" rel="noopener noreferrer">参考职业任务 · O*NET ↗</a></div></article>`).join('')}<details><summary>这些方向是怎样选出的？</summary><p class="fine-print">每个方向对应三项优势：取三项原始分之和，再为其中每项前四优势加 3 点探索优先权，选出排序靠前的三个方向；同分按预设列表顺序展示，不表示适合程度存在差异。此映射由本游戏编写，O*NET 仅提供职业任务参考，并未验证本卡牌与职业的对应关系。</p></details></section></div>
 <div class="result-actions"><p>回想一件让你投入又有成就感的事：你当时用到了哪项优势？</p><div><button class="quiet" data-action="edit">← 返回调整</button><button class="primary" data-action="restart">重新探索 ↻</button></div></div>`;bind();const start=performance.now();function tick(now){const t=Math.min(1,(now-start)/1000);document.querySelectorAll('[data-score]').forEach(el=>el.textContent=Math.round(Number(el.dataset.score)*(1-(1-t)**3)));if(t<1&&state.phase==='results')requestAnimationFrame(tick)}requestAnimationFrame(tick)
}
const dialog=document.createElement('dialog');dialog.className='modal';dialog.innerHTML='<div class="modal-heading"><h2 id="dialog-title"></h2><button id="close-dialog" class="quiet" aria-label="关闭弹窗">✕</button></div><div id="dialog-body"></div>';dialog.setAttribute('aria-labelledby','dialog-title');document.body.append(dialog);document.querySelector('#close-dialog').onclick=closeDialog;dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
const statusEl=document.createElement('div');statusEl.id='status';statusEl.setAttribute('role','status');statusEl.setAttribute('aria-live','polite');document.body.append(statusEl);
function openDialog(title,body){document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-body').innerHTML=body;dialog.showModal()}function closeDialog(){dialog.close()}
document.querySelector('#rules-button').onclick=()=>openDialog('优势卡牌 · 玩法说明',`<p class="rule-lead">27 张卡片 · 9 项优势 · 每项 3 张</p><ol class="rules"><li><h3>读正面，想真实的自己</h3><p>以最近半年的日常表现为参考，综合一张卡片上的全部描述判断。不要只按理想中的自己选择。正面是行为描述；点击翻面，可查看优势名称、发光面与阴影面。</p></li><li><h3>按 5 / 3 / 1 / 0 初步分类</h3><p>把全部卡片放入四行：非常符合 5 分、比较符合 3 分、一般符合 1 分、不太符合 0 分。每行暂时最多 12 张。电脑可拖动，也可点击分数；手机可点选卡片后点击分类按钮。</p></li><li><h3>让四行尽量均匀</h3><p>27 张牌无法四等分，本网页将“每行尽量七张”落实为三行各 7 张、一行 6 张，哪行留 6 张均可。比较同一行里的卡片，把相对不符合的下移、相对更符合的上移；不会自动替你判断。</p></li><li><h3>相加计分，揭晓前四</h3><p>将同一优势的三张卡片分数相加，每项为 0–15 分，按总分降序排名。阴影面、发光面不额外加减分。若并列跨越第 4 名，你可从同分项中选择优先探索项，原始得分与并列名次不变。</p></li><li><h3>把结果带回生活</h3><p>查看前四优势、全部排名与职业探索建议，并用实际经历验证。结果是本轮自我描述与取舍的记录，不是能力认证。卡牌的阴影面是复盘提示，不代表你必然具有这些问题。</p></li></ol><p class="fine-print">根据用户提供的卡牌与玩法整理。本网页为独立体验版本，非优势星球官方产品。职业方向由本游戏另行设计。</p>`);
const saveBar=document.createElement('div');saveBar.className='save-bar';saveBar.innerHTML='<span id="save-label" role="status"></span><button class="text-button" id="history-button">历史结果</button>';app.before(saveBar);
document.querySelector('#history-button').onclick=showHistory;
function saveProgress(){const ok=StrengthStorage.save(state);const el=document.querySelector('#save-label');if(el){el.textContent=ok?'已自动保存在此浏览器 · 刷新后可继续':'此浏览器暂时无法保存，请勿关闭页面';el.classList.toggle('save-failed',!ok)}const button=document.querySelector('#history-button');if(button)button.textContent='历史结果（'+StrengthStorage.results().length+'）'}
function showHistory(){const records=StrengthStorage.results();openDialog('历史评分结果', '<p>记录只保存在当前设备的这个浏览器中，最多保留最近 30 份不同结果。清除网站数据或使用无痕模式可能丢失记录。</p>'+(!records.length?'<p class="history-empty">还没有已提交的结果。完成分类并揭晓优势后，这里会自动留下记录。</p>':records.map((r,i)=>'<article class="history-card"><h3>'+new Date(r.completedAt).toLocaleString('zh-CN')+'</h3><div class="chips">'+r.top.map(id=>'<span style="color:'+GROUPS[id].color+'">'+GROUPS[id].name+'</span>').join('')+'</div><button class="text-button" data-record="'+i+'">查看完整评分 →</button></article>').join('')));document.querySelectorAll('[data-record]').forEach(button=>button.onclick=()=>{const r=records[Number(button.dataset.record)],scores=StrengthStorage.scores(r.places);openDialog('历史结果 · '+new Date(r.completedAt).toLocaleDateString('zh-CN'),'<p>这份记录不会覆盖你当前的分类进度。</p>'+GROUPS.map((g,id)=>({g,id,score:scores[id]})).sort((a,b)=>b.score-a.score||a.id-b.id).map(x=>'<div class="history-score"><span style="color:'+x.g.color+'">'+x.g.name+(r.top.includes(x.id)?' ✦':'')+'</span><strong>'+x.score+' / 15</strong></div>').join('')+'<button id="back-history" class="text-button">← 返回历史记录</button>');document.querySelector('#back-history').onclick=showHistory})}
const saved=StrengthStorage.load();if(saved)Object.assign(state,saved,{selected:null,flipped:false});
render();if(StrengthStorage.message())notify(StrengthStorage.message());
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}};register({name:'read_strength_game',description:'读取当前阶段、卡片行为描述、四行分配和计分。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({phase:state.phase,cards:CARDS.map(c=>({id:c.id,descriptions:c.lines,row:state.places[c.id]})),rows:ROWS.map((r,i)=>({...r,count:counts()[i]})),balanced:balanced(),ranking:state.phase==='results'?ranking().map(g=>({name:g.name,score:g.score})):null})});register({name:'move_strength_card',description:'将指定卡片放入一行分类；行索引0/1/2/3分别是5/3/1/0分。',inputSchema:{type:'object',properties:{cardId:{type:'integer',minimum:0,maximum:26},row:{type:'integer',minimum:0,maximum:3}},required:['cardId','row'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input!=='object')throw Error('需要卡片与分类');const moved=moveCard(input.cardId,input.row);return{moved:moved!==false,counts:counts(),placed:placed()}}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
